- src/interactors/crates.rs
- src/interactors/mod.rs
Provide the `User-Agent` header in every request from the server.
This became required by crates.io, which would otherwise forbid the request.
Resolves #38.
> Add User-Agent to all requests

- src/interactors/crates.rs
- src/parsers/manifest.rs
Example crates that failed before:
* http://localhost:8080/crate/lettre/0.10.0-alpha.2
* http://localhost:8080/repo/github/lettre/lettre
> Add support for 2018 edition crate renaming

- Cargo.lock
- Cargo.toml
Currently some projects, including our own repository, still fail to analyze with error `the given version requirement is invalid at line 1 column 2617`
The issue comes from [here](https://github.com/deps-rs/deps.rs/blob/66fd6850628073702a5b3517987902a060ece878/src/interactors/crates.rs#L126), where we parse the crates.io index, because `semver::Version` fails to parse.
The problem comes from releases like [`hyper 0.13.0-alpha.3`](https://github.com/rust-lang/crates.io-index/blob/2540ae4c8b7afdc08f1b9eac9ea5198eefac0ba2/hy/pe/hyper#L182), which require _exact_ versions of dependencies (futures-channel-preview `= 0.3.0-alpha.19` in this example).
I'll investigate the issue further in the following days.
> Downgrade semver crate to 0.10

- .github/workflows/premerge.yml
- .travis.yml
- libs/badge/badge.rs
This PR adds the initial CI configuration for the build, test, and lint cycle.
- Scheduled builds on `main` (except linting)
- Clippy lints reported as annotations ([example](https://github.com/deps-rs/deps.rs/pull/49/checks?check_run_id=1205495976)).
Future PRs can introduce: 
- Build caching to speed up builds (using https://github.com/actions/cache, taking care with nightly toolchains).
- Test coverage collection and reporting
- `cargo audit` runs to collect and report security vulnerabilities
> Initial GitHub Actions CI configuration

- Cargo.lock
- Cargo.toml
- src/engine/fut/analyze.rs
- src/engine/machines/analyzer.rs
- src/interactors/crates.rs
- src/interactors/github.rs
- src/interactors/mod.rs
- src/interactors/rustsec.rs
- src/main.rs
- src/server/mod.rs
- src/utils/cache.rs
when hitting `http://localhost:8080/repo/github/deps-rs/deps.rs/status.svg`
logs before:
```
Server running on port 8080
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:45.829592+01:00","version":"0.1.0"}
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:46.540504+01:00","version":"0.1.0"}
{"msg":"cache hit","level":"DEBG","ts":"2020-10-03T19:02:46.541233+01:00","version":"0.1.0"}
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:46.757033+01:00","version":"0.1.0"}
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:47.057713+01:00","version":"0.1.0"}
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:47.291556+01:00","version":"0.1.0"}
{"msg":"cache miss","level":"DEBG","ts":"2020-10-03T19:02:47.578993+01:00","version":"0.1.0"}
{"msg":"cache …
```
> improve logging

- Cargo.lock
- Cargo.toml
- src/engine/mod.rs
- src/utils/cache.rs
This also improves our throughput, because we're not holding an exclusive lock for the entire duration of the request
> Remove Mutex around Cache and move away from deprecated lru-cache

- src/engine/mod.rs
- src/models/crates.rs
- src/server/views/html/status.rs
This PR closes #35 by excluding `dev-dependencies` from the project assessment. An example to test this on can be the `telegram-bot` package:
> http://localhost:8080/crate/telegram-bot/0.7.0
As we have discussed, we may also want to be able to remove build dependencies from the badge, but I figured that this might be something for a different PR.
I will request two reviews, whoever reviews it first may merge afterwards (also feel free to self-request a review!). :)
> Remove dev-dependencies from badge

- src/server/views/html/status.rs
I have also removed the part showing the number of up-to-date crates as I think it's not that informative and can easily be figured out from the other information.
> Show number of outdated dependencies even if insecure crates are present

- .github/workflows/deployment.yml
- deploy/base/deployment.yaml
- deploy/base/ingress.yaml
- deploy/base/kustomization.yaml
- deploy/base/service.yaml
- deploy/overlays/production/kustomization.yaml
- deploy/overlays/production/patch-ingress.json
- deploy/overlays/staging/kustomization.yaml
- deploy/overlays/staging/patch-ingress.json
Finally managed to get everything working
This adds Kubernetes manifests using Kustomize, and deploy on push to main using ArgoCD
Currently, it will deploy to https://staging.deps.rs on every push to main, I can change it to deploy to the production URL, or keep as is and find another way to deploy production, either a separate branch, or on tagged releases
I've created a team named `argocd-read-only`, feel free to add yourself there, it will give you access to the ArgoCD setup (link in the team description)
> CD: deploy to kubernetes

- src/engine/mod.rs
Update popular repositories blocklist
* Updates the [xi-editor](https://github.com/xi-editor/xi-editor) repository url
* Adds [996.ICU](https://github.com/996icu/996.ICU)
* Updates [rustlings](https://github.com/rust-lang/rustlings) repository url
These repositories shouldn't belong to the homepage, since they aren't really crates and deps.rs fails to analyze them.
This gives space to:
* https://github.com/starship/starship
* https://github.com/SergioBenitez/Rocket
> Update popular repositories blocklist

- src/interactors/crates.rs
Fixes a mistake I made in [#69](https://github.com/deps-rs/deps.rs/pull/69/files#diff-3cbeff58e0bfae417a9490e5dcc6a391a382ee4f0f00073fc0376117200cbfd4), which resulted into dev dependencies for crates.io-index crates being counted as normal dependencies
Before and After
> Fix dev dependencies being counted as main dependencies

- src/models/crates.rs
- src/server/views/html/status.rs
and a crates link is provided on the icon to the left
> links direct to other deps.rs pages

- Cargo.lock
- Cargo.toml
- src/engine/machines/analyzer.rs
- src/models/crates.rs
- src/server/views/html/status.rs
This PR adds functionality to close #75.
RustSec advisories affecting a repository are now listed with some additional information at the bottom of the page. This encompasses the description of the CVE, a list of unaffected and fixed versions as well as a link to the RustSec page (which I have to generate manually based on their URL scheme so pray that this will never change).
- I bumped the `rustsec` crate version to the latest release. Since I was going to touch most of the code using this crate anyway I thought using the most up-to-date version would be wise.
- I added `pulldown-cmark` as a dependency to render the CVE descriptions (which are markdown). This might be a bit overkill, but if anybody knows a maintained, well-functioning, small Markdown renderer raise your hands. 😄
I …
> Display rustsec information on page

- src/server/mod.rs
Before:
```
/path  => Route::Path
/path/ => 404
```
After:
```
/path  => Route::Path
/path/ => Route::Path
```
> trim path trailing slashes before route match

- Cargo.lock
- Cargo.toml
- build.rs
- src/server/assets.rs
- src/server/mod.rs
- src/server/views/html/mod.rs
Before starting the work on updating our css (as mentioned in #96), I think we should setup [cache busting](https://www.keycdn.com/support/what-is-cache-busting), in order to make sure browsers always get the latest version of the css.
This is implemented by ~~appending a "useless" query string parameter to the `style.css` import with the sha1 digest of it's contents~~  adding the sha1 digest of the contents of `style.css` to its path.
With this change implemented the following issues will be resolved:
* Everybody always downloads the most up to date css file, independent of any browser or CDN caching
* We can have longer cache times, since newer versions of the css will be at a different url
> Setup cache busting for style.css

- Cargo.lock
- Cargo.toml
- assets/styles/fa.sass
- assets/styles/main.sass
- src/server/views/html/mod.rs
- src/server/views/html/status.rs
This cuts off about 100 kBs between CSS and font files used for the Font Awesome icons. Instead of importing a huge font file that contains all of the icons, the few icons that we use are inlined into the HTML as SVGs.
Also this upgrades us to Font Awesome 5.
_https://deps.rs/repo/github/rusoto/rusoto was used for this test, which is a bit of an extreme example because of the number of crates in the workspace_
|       | Uncompressed | gzip -9 |
| ----------- | ----------- | -------------|
| Before      | 648 kB       | 12 kB |
| After   | 1.2 MB        | 16 kB |
> Use font-awesome-as-a-crate instead of importing the entire Font Awesome library

- Cargo.lock
- Cargo.toml
Also fixes the insecure badge because of [RUSTSEC-2021-0020](https://rustsec.org/advisories/RUSTSEC-2021-0020.html).
I'm not sure what `cadence` does, so I haven't tested it.
> Update cargo dependencies

- src/server/mod.rs
- src/server/views/html/error.rs
This small PR introduces a very simple `404 error` page to indicate to the user that something went wrong rather than producing just a blank page, as before. This should close #90.
> feat: add 404 page

- src/models/crates.rs
> clippy: fix clippy::from_over_into warning

- src/engine/machines/analyzer.rs
This PR filters yanked advisories in the matching process to avoid false positives. See #108 for more details.
> Filter yanked advisories (#108)

- Cargo.lock
- Cargo.toml
- src/engine/machines/analyzer.rs
- src/server/views/html/status.rs
Both are now based on `semver` v1, so it should be safe to bring them in.
The code was adapted to changes in `rustsec`.
- Advisory metadata `yanked` is seemingly now called `withdrawn`
- Versions `unaffected` and `patched` are now retrieved via method calls
> Update dependencies crates-index and rustsec

- src/models/repo.rs
- src/server/views/html/status.rs
Sourcehut git projects (https://git.sr.ht) are supported with the repo specifiers
/repo/sr.ht/~user/project
/repo/srht/~user/project
/repo/sourcehut/~user/project
This solves feature request #115.
(Note that sourcehut also offers mercurial/hg hosting at https://hg.sr.ht which is not supported.)
> Add support for projects hosted on sourcehut (sr.ht)

- README.md
This is an addendum to the now-merged PR #117 which actually implemented the support.
> Mention SourceHut support in README.md

- src/engine/mod.rs
- src/models/crates.rs
- src/server/views/badge.rs
- src/server/views/html/status.rs
This pull request creates a new distinction between dependencies which are
- _always insecure_: shown in red, where even the latest version (in range) of a dependency is not patched;
-  _possibly insecure_: (has at least one vulnerability in any version in the range) 
Resolves #94 ~~, and also reduces the number of queries to the advisory DB.~~
Summary:
- Update project status page
- show always insecure dependencies as insecure, and remaining ones as "possibly insecure"
- show warning sign on all dependencies with possible vulnerability
- tweak security banner in case all insecure dependencies are "possibly insecure"
- Update badge
- Only show the red "insecure" if at least one dependency is always insecure
- show "possibly insecure" if all are up to date but might be vulnerable
> Only query advisory database on latest matching version

- Cargo.lock
- Cargo.toml
Bumps all dependencies except crates-index, since rustsec hasn't updated it yet on their side
> Bump all dependencies except crates-index

- README.md
- libs/badge/badge.rs
Larger, uppercase, flat style supported by shields.io:
> Add for-the-badge style and docs

- src/engine/machines/analyzer.rs
> Use `crate_scope` in advisory query

- src/utils/index.rs
This makes it so that if the crates.io-index takes more than the update interval to update (currently 20 seconds), the `time::Interval` doesn't try to poll the index straight way. I don't know if this might have been the cause of our current issues but I've been finding that the default `Burst` behavior is wrong for most use-cases, so I'm modifying it everywhere `time::interval` is used.
Previous behavior: https://docs.rs/tokio/1.20.1/tokio/time/enum.MissedTickBehavior.html#variant.Burst
New behavior: https://docs.rs/tokio/1.20.1/tokio/time/enum.MissedTickBehavior.html#variant.Delay
> Use `MissedTickBehavior::Delay` for updating crates.io-index

- Cargo.lock
- src/engine/fut/crawl.rs
Includes `crossbeam`, `futures` and `rustsec` updates
> cargo: bump dependencies

- README.md
- src/models/repo.rs
- src/server/mod.rs
- src/server/views/html/index.rs
- src/server/views/html/status.rs
deps.rs is now available for self-hosted Gitea at
`/repo/gitea/<DOMAIN>/owner/repo`, e. g.
`/repo/gitea/git.example.org/deps-rs/deps.rs`,
`/repo/gitea/git.example.org:1234/deps-rs/deps.rs`,
`/repo/gitea/http://unsafe-gitea.org/deps-rs/deps.rs`.
This _should_ also include support for Gitea hosted in subdirectories,
e. g. `www.example.org/gitea`, though I haven't tested this yet.
If no protocol (`https://`/`http://`) is specified, `https://` is
automatically added to the beginning of the gitea server's URL.
However I could also change this to only accept https. Another
option might be the use of URL-encoding.
I am open for feedback, feel free to suggest changes.
Implementation notes:
- The Router now matches `/repo/*site/:qual/:name` instead of
`/repo/:site/:qual/:name` to allow for an …
> Support for self-hosted Gitea

- src/models/repo.rs
- src/server/views/html/status.rs
I changed the FontAwesome icons for Codeberg and Gitea to better approximate their logos. Screenshots are below.
I also addressed the two Linter errors I oversaw when merging #164 because the CI run showed an internal permission error instead.
---
> Set new icons for Codeberg and Gitea

- assets/styles/bulma/README.md
- assets/styles/bulma/components/card.sass
- assets/styles/bulma/components/dropdown.sass
- assets/styles/bulma/components/level.sass
- assets/styles/bulma/components/navbar.sass
- assets/styles/bulma/components/pagination.sass
- assets/styles/bulma/components/panel.sass
- assets/styles/bulma/elements/box.sass
- assets/styles/bulma/elements/button.sass
- assets/styles/bulma/elements/content.sass
- assets/styles/bulma/elements/icon.sass
- assets/styles/bulma/elements/notification.sass
- assets/styles/bulma/elements/other.sass
- assets/styles/bulma/elements/table.sass
- assets/styles/bulma/elements/title.sass
- assets/styles/bulma/form/file.sass
- assets/styles/bulma/form/select.sass
- assets/styles/bulma/grid/columns.sass
- assets/styles/bulma/grid/tiles.sass
- assets/styles/bulma/helpers/spacing.sass
- assets/styles/bulma/helpers/typography.sass
- assets/styles/bulma/layout/hero.sass
- assets/styles/bulma/layout/section.sass
- assets/styles/bulma/utilities/derived-variables.sass
- assets/styles/bulma/utilities/extends.sass
- assets/styles/bulma/utilities/functions.sass
- assets/styles/bulma/utilities/initial-variables.sass
- assets/styles/bulma/utilities/mixins.sass
This updates the Bulma version used by the project to revision [`514229c985e0146039d6960a220f317876c39f8d`](https://github.com/jgthms/bulma/tree/514229c985e0146039d6960a220f317876c39f8d).
This changes the color scheme slightly as it now uses slightly more muted colors:
> Bump vendored Bulma version

- src/server/views/html/mod.rs
Until now, we served all HTML documents in [Quirks Mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode) which solely exists for backwards-compatibility with web pages from the age of Netscape Navigator 4 and IE 5.
I suppose we don't want that, which is why I fixed this by setting the proper `<!DOCTYPE html>` in all served pages.
> Quirks Mode no more!

- assets/links.js
- assets/styles/main.sass
- build.rs
- src/server/assets.rs
- src/server/mod.rs
- src/server/views/html/index.rs
Since the project by now supports numerous different hosters and also self-hosted Gitea repositories, I decided to add two link generators to the front page:
This should also simplify the addition of features like nestes project paths (#95), at least from an End-User perspective.
I added a new function to generate the forms and some JS to create the links to reduce load on the server for a redirect.
I am not a front-end person! If you see this and feel it's garbage, feel free to point out problems/address them yourself. :)
This has also literally been the first 31 SLoC Javascript in my whole life, so review with caution. 😄
> Add link generators to the front page

- Cargo.lock
- Cargo.toml
- src/server/views/html/status.rs
Updates us to Font Awesome 6 and to the latest version of maud.
I have https://github.com/lambda-fairy/maud/pull/358 to get maud on the latest version of itoa, as 0.4 used `mem::uninitialized`
> cargo: update dependencies

- deploy/base/deployment.yaml
Would this be ok for you as a way of detecting when GitHub starts timing out and making it restart the server?
If so I'll have to change that page because we currently seem to reply with a 200 even when there's an error.
> Point the livenessProbe at /repo/github/deps-rs/deps.rs

- assets/links.js
- src/engine/mod.rs
- src/server/mod.rs
- src/server/views/badge.rs
- src/server/views/html/index.rs
- src/server/views/html/status.rs
This PR will allow people to analyze crates that do not live in the root of a repository.
The main work for that had already been done, convenience functions were already in place for constructing links referring to sub-directory.
Hence, these are the main changes:
- update parser and scheme for Query Parameters (that were so far only used to describe Badge Styling)
- adjust the link generator to generate the new links accordingly.
- make the directory structure location visible in the report
- update svg link generation to reflect possible sub-directory structures
This will close #95.
The chosen link scheme looks as follows:
```
https://deps.rs/repo/<HOSTER>/<USER>/<REPO>?path=[...]
```
I do realize that this could've been done with a `/<PATH>` argument instead but I thought that this is …
> Allow analyzing crates in sub-directories of repo root

- src/engine/mod.rs
Query crate from the local crates.io index clone: **10s** (unchaged)
Get popular crates from crates.io: **2m -> 15m**
Get popular repos from github: **2m -> 5m**
Fetch advisory db: **30m** (unchanged)
> Tweak cache durations

- .github/workflows/premerge.yml
- Cargo.lock
- Cargo.toml
- src/engine/machines/analyzer.rs
sadly, git2 security upgrade is still dependent on https://github.com/rustsec/rustsec/pull/801
> Update deps + clippy

- Dockerfile
Fixes the breakage caused by #198
> docker: add missing libcurl dependency

- Cargo.lock
- Cargo.toml
- build.rs
This replaces [sass-rs](https://crates.io/crates/sass-rs), which hasn't seen updates in at least 2 years with the pure Rust grass reimplementation
> Replace sass-rs with grass

- Cargo.lock
- Cargo.toml
- src/models/repo.rs
I was trying to upgrade reqwest and hyper in one pull request, but hyper upgrade required too many changes, so I'd like to upgrade reqwest first
> Bump reqwest from 0.11 to 0.12

- Cargo.lock
- Cargo.toml
- README.md
- src/server/mod.rs
- src/server/views/badge.rs
- src/utils/common.rs
- src/utils/mod.rs
> Support custom subject text

- Cargo.lock
- Cargo.toml
- src/engine/fut/crawl.rs
- src/engine/mod.rs
- src/interactors/crates.rs
- src/interactors/github.rs
- src/interactors/mod.rs
- src/interactors/rustsec.rs
- src/main.rs
- src/models/repo.rs
- src/server/assets.rs
- src/server/error.rs
- src/server/mod.rs
- src/server/views/badge.rs
- src/server/views/html/error.rs
- src/server/views/html/index.rs
- src/server/views/html/mod.rs
- src/server/views/html/status.rs
- src/utils/cache.rs
full-fat Actix Web conversion including (somewhat necessary) improvements to error handling
pros:
- –91 LoC (smallest final result)
- clearer error handling
- we can use automatic HTTP/2 connections from the reverse proxy if we want to
- access to large library of first- and third-party middleware
cons:
- biggest diff
tokei:
```
Language            Files        Lines         Code     Comments       Blanks
===============================================================================
Rust                   31         3861         3324           21          516
|- Markdown             5           47            0           42            5
(Total)                           3908         3324           63          521
```
> refactor: migrate web server to Actix Web

- Cargo.lock
- Cargo.toml
- src/engine/mod.rs
- src/main.rs
I've always wandered what is was for. Nothing :smile:.
> refactor: drop unused `cadence` metrics

- src/server/mod.rs
https://deps.rs/aaaa currently misleadingly returns 200.
> fix: set status code to 404 for the not found page

- Cargo.lock
- Cargo.toml
- src/utils/index.rs
This fixes the `crates-index` problem we've been having since they switched from libgit2 to `gix`. The issue is caused by `gix` not supporting garbage collection, which is necessary when constantly updating the same repository over a long period of time. It's like vacuum in PostgreSQL, for those who have experienced it.
This is fixed in the following way:
1. After ~1 hour of running the server, the `gix` internal slotmap runs out of space. `gix` can't currently expand it in place, so we close the crates.io-index repository instance and reopen it. This will temporarily solve the problem by growing the slotmap.
2. After many hours, the number of packs grows too much. At this point git would have forced a gc, but `gix` doesn't support it. I don't want to use libgit2 or call the git CLI, …
> Deal with forever increasing number of packs when pulling crates.io-index

- src/engine/mod.rs
- Updated the `Engine::find_latest_stable_crate_release` method to filter out yanked releases.
- Now, only the latest **non-yanked** version will be selected for redirection.
- If all versions are yanked, the method returns `None`, resulting in a 404 or CrateFetchFailed error upstream.
- Close [Issue #256](https://github.com/deps-rs/deps.rs/issues/256)
Previously, the `/crate/{crate_name}` route would redirect to the latest version, even if it was yanked. This behavior is inconsistent with crates.io, docs.rs, and other Rust ecosystem tools, and may mislead users into using yanked (unrecommended) versions. With this change, only non-yanked versions are considered for redirection, aligning with community expectations.
1. Run the project locally with `cargo run`.
2. Visit …
> fix: filter out yanked releases in engine

- Cargo.lock
- Cargo.toml
This disables the following features for actix-web:
1. `compress-brotli`: I usually disable this given that zstd has reached 71% global usage [^1]. brotli is also slow to compress.
2. `cookies`: we don't use them
And the `derive` feature of `actix-web-lab`, which we don't need.
[^1]: https://caniuse.com/zstd
> Reduce `actix-web*` features

- Dockerfile
This reduces the size of the final image from 155 MB to 111 MB
> Switch Docker image to slim variant of Debian
